name: Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 every Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate sitemap
      run: python sitemap_generator.py
      
    - name: Create tag
      id: create_tag
      run: |
        timestamp=$(date +%Y%m%d)
        echo "tag_name=sitemap-${timestamp}" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: sitemap.xml
        tag_name: ${{ steps.create_tag.outputs.tag_name }}
        name: Sitemap Update ${{ steps.create_tag.outputs.tag_name }}
        body: Automated sitemap generation
