name: Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 every Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate sitemap
      run: python sitemap_generator.py
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: sitemap-${{ github.run_number }}
        release_name: Sitemap Update ${{ github.run_number }}
        body: |
          Automated sitemap generation for week ${{ github.run_number }}
        draft: false
        prerelease: false
        
    - name: Upload Sitemap
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sitemap.xml
        asset_name: sitemap.xml
        asset_content_type: application/xml
