name: Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 every Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate sitemap
      run: python sitemap_generator.py
      
    - name: Update latest tag
      run: |
        git tag -f latest
        git push origin -f latest
        echo "tag_name=latest" >> $GITHUB_OUTPUT
      id: update_tag
        
    - name: Create/Update Release
      uses: softprops/action-gh-release@v1
      with:
        files: sitemap.xml
        tag_name: latest
        name: Latest Sitemap
        body: |
          Automated sitemap generation
          Last updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
        draft: false
        prerelease: false
